<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="PhonesTable.aspx.cs" Inherits="PhonesTable" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
    Phones Manger
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="contentBody" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="True" CssClass='Grid' Height="171px"  Width="600px" AutoGenerateDeleteButton="True" DataKeyNames="id" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnDataBound="GridView1_DataBound" OnRowDataBound="GridView1_DataBound" AllowSorting="True" PageSize="15">
    <HeaderStyle CssClass='GridHeader'></HeaderStyle>
    <AlternatingRowStyle CssClass='GridAtlItem'/>
    </asp:GridView>    
</asp:Content>

